abstract: Everything you need to follow the Catalyst Tutorial
build_requires: 
  ExtUtils::MakeMaker: 6.11
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Task-Catalyst-Tutorial
no_index: 
  directory: 
    - examples
    - inc
    - t
requires: 
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Plugin::Authentication: 0.09
  Catalyst::Plugin::Authentication::Store::DBIC: 0.07
  Catalyst::Plugin::Authorization::ACL: 0.08
  Catalyst::Plugin::Authorization::Roles: 0.04
  Catalyst::Plugin::ConfigLoader: 0.13
  Catalyst::Plugin::HTML::Widget: 1.1
  Catalyst::Plugin::Session: 0.12
  Catalyst::Plugin::Session::State::Cookie: 0.05
  Catalyst::Plugin::Session::Store::FastMmap: 0.02
  Catalyst::Plugin::StackTrace: 0.06
  Catalyst::Plugin::Static::Simple: 0.14
  Catalyst::Runtime: 5.7000
  Catalyst::View::TT: 0
  DBIx::Class: 0
  DBIx::Class::Schema: 0
  Test::More: 0
version: 0.01
